# Generated by Django 4.2.11 on 2024-04-15 20:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
            ],
            options={
                'db_table': 'Employees',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('price', models.FloatField(default=1000)),
            ],
            options={
                'db_table': 'Room_types',
            },
        ),
        migrations.CreateModel(
            name='Tax_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=50)),
                ('tax_percent', models.IntegerField()),
            ],
            options={
                'db_table': 'Tax_rate',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room_type')),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
        migrations.AddField(
            model_name='room_type',
            name='tax_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tax_rate'),
        ),
        migrations.CreateModel(
            name='Room_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rooms')),
            ],
            options={
                'db_table': 'Room_reviews',
            },
        ),
        migrations.CreateModel(
            name='Room_pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('room_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.room_type')),
            ],
            options={
                'db_table': 'Room_pricing',
            },
        ),
        migrations.CreateModel(
            name='Room_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room_type')),
            ],
            options={
                'db_table': 'Room_images',
            },
        ),
        migrations.CreateModel(
            name='Room_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=50)),
                ('feature', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('room_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.room_type')),
            ],
            options={
                'db_table': 'Room_features',
            },
        ),
        migrations.CreateModel(
            name='Room_availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rooms')),
            ],
            options={
                'db_table': 'Room_availability',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('check_out_date', models.DateField()),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.employees')),
                ('reserved_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rooms')),
            ],
            options={
                'db_table': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.TextField()),
                ('reported_on', models.DateTimeField()),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='not completed', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.reservations')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Customer_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'db_table': 'Customer_Rating',
            },
        ),
        migrations.CreateModel(
            name='customer_personal_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifcation_number', models.IntegerField()),
                ('verified', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'db_table': 'customer_personal_data',
            },
        ),
    ]
