# Generated by Django 3.2.25 on 2024-04-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_personal_data',
        ),
    ]
