# Generated by Django 3.2.25 on 2024-04-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_customer_personal_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_personal_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifcation_number', models.IntegerField()),
                ('verified', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'db_table': 'customer_personal_data',
            },
        ),
    ]
